server:
  port: 8200
spring:
  profiles:
    active: '@profiles.active@'
  application:
    name: xpack-permissions
  messages:
    basename: i18n/permissions
    encoding: UTF-8

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  file:
    path: /opt/dataease2.0/log/${spring.application.name}
