spring:

  datasource:
    url: jdbc:mysql://localhost:3306/de_official?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 1qaz@WSX
