server:
  port: 8100
spring:
  profiles:
    active: '@profiles.active@'
  application:
    name: core-backend


mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  file:
    path: /opt/dataease2.0/log/${spring.application.name}
