server:
  port: 8100
spring:
  profiles:
    active: '@profiles.active@'
  application:
    name: core-backend
  messages:
    encoding: UTF-8
  main:
    allow-circular-references: true
  cache:
    type: jcache
    jcache:
      config: classpath:ehcache/ehcache.xml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
management:
  health:
    redis:
      enabled: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  file:
    path: /opt/dataease2.0/log/${spring.application.name}
# sql日志生产环境注释掉
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
