spring:
  datasource:
    url: jdbc:mysql://123.56.8.132:33061/jinlong?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: Calong@2015
  messages:
    basename: i18n/core,i18n/permissions
  flyway:
    enabled: true
    table: de_standalone_version
    validate-on-migrate: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true


